In [2]:
import numpy as np

In [3]:
array = np.array([1,8,2,6,4,12,21])
array

array([ 1,  8,  2,  6,  4, 12, 21])

All the comma separated values are of the same width and right aligned. Since the maximum number, 21, occupies 2 positions, all the other values are formatted as two-character fields. So now you know why there is a leading space between the [ and the 1.

In [4]:
array2x3 = np.array([[1,2,3], [10,20,30]])
array2x3

array([[ 1,  2,  3],
       [10, 20, 30]])

The format of the output is based on the number of dimensions, aligning the columns within each row: as we can see the 1 and 10 are aligned, the 2 and 20 etc.

In [5]:
array2x3.shape

(2, 3)

In [7]:
array2x3.ndim

2

In [8]:
len(array2x3)

2

The ndim is the same as the number of axes or the length (len) of the output of the array’s shape:

In [9]:
array2x3.size

6

As NumPy is written in C, it uses its data types. As such integers are stored as int64 values — which correspond to 64-bit (i.e. 8-byte) integers in C.

In [10]:
array2x3.dtype

dtype('int64')

In [11]:
array2x3.itemsize

8

the number of bytes required to store each element, by accessing the itemsize:

In [12]:
array2x3.nbytes

48

The memory footprint (nbytes)is the number of elements times the number of bytes.````````````````````````

#### To fill an array with specific values, NumPy provides three special functions: zeros, ones and full, which respectively create arrays containing 0s, 1s or a specified value. Please note that zeros and ones contain float64 values, but we can obviously customise the element type.

In [13]:
zeros1d = np.zeros(5)
zeros1d

array([0., 0., 0., 0., 0.])

In [14]:
zeros1d_int = np.zeros(5, dtype =int)
zeros1d_int

array([0, 0, 0, 0, 0])

In [16]:
ones = np.ones((2,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
full = np.full((2,5),7)
full

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

### NumPy provides optimised functions for creating arrays from ranges. The two most important functions to create evenly spaced ranges are arange and linspace, for integers and floating points respectively.

◼️ Integers: Given the interval
np.arange(start, stop, step): Values are generated within the half-open interval [start, stop) — i.e. the interval including start but excluding stop. The default start value is 0 and the default step size is 1.



In [18]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [21]:
np.arange(2,8, 2)

array([2, 4, 6])

In [22]:
np.arange(8, -2, -1)

array([ 8,  7,  6,  5,  4,  3,  2,  1,  0, -1])

### ◼️ Floats: Given the number of elements
np.linspace(start, stop, num, endpoint): Returns num evenly spaced samples, calculated over the interval [start, stop]. The endpoint of the interval can optionally be excluded. The default num value is 50 and the default endpoint is True.

    5 evenly spaced elements from 1.0 to 2.0 (excluding 2.0):
    np.linspace(1, 2, num = 5, endpoint = False)
    5 evenly spaced elements from 1.0 to 2.0 (including 2.0):
    np.linspace(1, 2, num = 5, endpoint = True)

In [25]:
np.linspace(1,2,5, endpoint = False)

array([1. , 1.2, 1.4, 1.6, 1.8])

In [26]:
np.linspace(1,2,5, endpoint =True)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

### Random Ranges

To generate random ranges, NumPy provides a few options, but here are the most popular:

◼️ Random samples from a uniform distribution over [0, 1)
np.random.rand(d0, d1, ...) where dn are the array dimensions:

    1D array with 5 random samples:
    np.random.rand(5)
    2D array with 2 rows and 5 random samples each:
    np.random.rand(2, 5)

In [27]:
np.random.rand(5)

array([0.61669921, 0.89355011, 0.16539001, 0.40722758, 0.53051147])

In [29]:
np.random.rand(2,5)

array([[0.68624879, 0.44069546, 0.08998777, 0.58068889, 0.37675948],
       [0.71883008, 0.89913562, 0.40538352, 0.72474659, 0.63369071]])

### ◼️ Random integers
np.random.randint(low, high, size): Returns random integers from low (inclusive) to high (exclusive). If high is None (the default), then results are from [0, low).

    10 random integers from 1 to 99:
    np.random.randint(low = 1, high = 100, size = 10)

In [30]:
np.random.randint(low =1, high =100, size =10)

array([85, 74, 95, 94, 40, 15, 36,  4, 47,  1])

### indexing

In [34]:
array2x3[1,-3]

10

### ➌ — Slicing

Slicing arrays results to a subset of the original elements, using the [first:last] notation, which returns a sub array with elements from index first to last-1.

→ If first is omitted, 0 is assumed, so the elements from the beginning till the last-1 are returned.


→ If last is omitted, the array’s length is assumed, so the elements from first till the end are returned.


→ If both first and last are omitted, the whole array is returned.

In [35]:
array[1:3]

array([8, 2])

In [36]:
array

array([ 1,  8,  2,  6,  4, 12, 21])

In [37]:
array[:-1]

array([ 1,  8,  2,  6,  4, 12])

##### Multi Dimensions

Similar principles are applied in the 2D arrays, so slicing uses this notation:
[row_first:row_last, column_first:column_last].

→ To select multiple rows we use: [row_first:row_last, :].
→ To select multiple columns we use: [:, column_first:column_last].

In [38]:
array2x3[0:1, 1:2]

array([[2]])

In [39]:
array2x3

array([[ 1,  2,  3],
       [10, 20, 30]])

In [40]:
array2x3[:, :1]

array([[ 1],
       [10]])

In [45]:
array2x3[1:, 1:2]

array([[20]])

### ➍ — Making Copies
Shallow Copy / View

Slicing does not modify the original array. The newly created array makes shallow copies (or views) of the original elements — that means it copies the elements’ references but not the objects they point to.

In other words, any modification to the newly created array will be reflected in the original array too.

In [49]:
original_arr = np.arange(0,10)
original_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
sub_arr = original_arr[5:]

In [51]:
sub_arr

array([5, 6, 7, 8, 9])

We observe that the original array and the sliced one are indeed two different objects, by using the built-in id function:
display(id(originalArray)) and display(id(subArray)).

In [52]:
display(id(original_arr))
display(id(sub_arr))

140590239773920

140590239791024

In [54]:
sub_arr[0] = sub_arr[0]*10

In [55]:
sub_arr

array([50,  6,  7,  8,  9])

In [56]:
original_arr

array([ 0,  1,  2,  3,  4, 50,  6,  7,  8,  9])

### Deep Copy

Although shallow copies save memory as they share data, sometimes it is necessary to create independent copies of the original data. This operation is called deep copying and is useful in multi-threading programming where separate parts of our program could attempt to modify the data at the same time — possibly corrupting it.

NumPy provides the method copy, which returns a new array object with a deep copy of the original array object’s data.

Repeating the previous example, we can see that the original array is not impacted when modifying the sub array.

In [60]:
new_arr = original_arr.copy()
new_arr

array([ 0,  1,  2,  3,  4, 50,  6,  7,  8,  9])

In [61]:
new_arr[5] = new_arr[5]*10
new_arr

array([  0,   1,   2,   3,   4, 500,   6,   7,   8,   9])

In [62]:
original_arr

array([ 0,  1,  2,  3,  4, 50,  6,  7,  8,  9])

### ➎ — Element-wise Operations

NumPy provides many operators which enable us to write simple expressions that perform operations on entire arrays. This is our stepping stone to becoming advanced later and eliminate for-loops in our programs!
With Scalar

We can perform element-wise arithmetic operations with arrays and scalars. During these operations the scalar is applied to every array element, so this snippet adds 5 to every element: array + 5.

Each operation returns a new array containing the result (i.e. does not modify the original array).

In [64]:
array

array([ 1,  8,  2,  6,  4, 12, 21])

In [65]:
array+5

array([ 6, 13,  7, 11,  9, 17, 26])

In [66]:
array +=1

In [67]:
array

array([ 2,  9,  3,  7,  5, 13, 22])

### 📌 Please note that array multiplication is not matrix multiplication. The elements are solely component-wise multiplied. Using the previous arrays, we can calculate the matrix multiplication by using the dot function:
np.dot(arrayA, arrayB)

In [68]:
arrayA = np.arange(2,12,2)
arrayA

array([ 2,  4,  6,  8, 10])

In [70]:
arrayB = np.arange(0,5)+1
arrayB

array([1, 2, 3, 4, 5])

In [72]:
np.dot(arrayA, arrayB)

110

### 📌 To compare complete arrays for equality we use the array_equal function, which returns True if two arrays have the same shape and same elements:
np.array_equal(compA, compB)

### ➏ — Broadcasting

So far these operations require as operands two arrays of the same size and shape. Broadcasting relaxes these constraints when the arrays’ shapes are compatible, enabling some concise and powerful manipulations.

The smaller array becomes ‘broadcast’ across the larger array. It allows us to avoid loops and also create unnecessary copies of our data.

Based on the official documentation:

    When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing dimensions, and works its way forward.
    Two dimensions are compatible when:
    • they are equal, or
    • one of them is 1
    If these conditions are not met, a ValueError: operands could not be broadcast together exception is thrown.

We will demonstrate the operating principles of broadcasting in a few of step-by-step multiplication examples. Pretty much, the smaller array ‘stretches’ so that it is multiplied with each row of the larger array.

    It is not literally stretched in memory; it is the computation that is repeated.

In [73]:
exA = np.array([[1,2,3],[4,5,6],[7,8,9]])
exA

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [74]:
exB = np.array([2,5,12])
exB

array([ 2,  5, 12])

In [75]:
exA * exB

array([[  2,  10,  36],
       [  8,  25,  72],
       [ 14,  40, 108]])

In [77]:
arr_re = np.arange(1,10)
arr_re

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
arr_re.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Resize

If we need to change the total number of elements, then we need to resize the array. If we are enlarging it, it will add trailing zeroes, until it reaches the new size. Otherwise it is truncated to the new size.

📌 The resize modifies the original array.



In [79]:
arr_re.resize(15, refcheck =False)

In [82]:
arr_re.resize(5, refcheck =False)

#### 📌 Another desired behaviour of enlarging an array is to have it repeat itself until it reaches the new size. In this case we can use this ‘static’ version of resize, which takes the original array as an input:
np.resize(array09, 10

In [84]:
np.resize(arr_re, 12)

array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2])

### New Dimension

Inserting a new axis into an array increases its dimensionality. newaxis is usually used to make arrays compatible for broadcasting.

In [85]:
arr1x4 = np.array([1,2,3,4])
print(arr1x4)
print(np.shape(arr1x4))

[1 2 3 4]
(4,)


In [86]:
arr4x1 = arr1x4[:, np.newaxis]
print(arr4x1)
print(np.shape(arr4x1))

[[1]
 [2]
 [3]
 [4]]
(4, 1)


### Flatten vs. Ravel

Flattening is the inverse operation to reshaping. We can flatten a multidimensional array into a single dimension with the methods flatten and ravel. Method flatten deep copies the original array’s data, while ravel shallow copies it, [as such flatten is slower].

In [87]:
arr2x2 = np.arange(1,5).reshape(2,2)
arr2x2

array([[1, 2],
       [3, 4]])

In [88]:
arr2x2.flatten()

array([1, 2, 3, 4])

In [89]:
arr2x2 = arr2x2.reshape(2,2)
arr2x2

array([[1, 2],
       [3, 4]])

In [92]:
arr2x2.ravel()    #not modify on original data

array([1, 2, 3, 4])

In [91]:
arr2x2

array([[1, 2],
       [3, 4]])

### Join

Joining or Concatenating means putting contents of two or more arrays in a single array, along a specified axis, by ‘stacking’ them under (axis = 1) or next to (axis = 0) each other. There are a few options to do that, but the concatenate function is the most popular.

In [93]:
arr1 = np.arange(9).reshape(3,3)
arr2 = arr1*2

In [96]:
np.concatenate((arr1, arr2), axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [98]:
# concatenate in horizontal stack axis=1
np.concatenate((arr1,arr2), axis =1)

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

### Split

Splitting is the reverse operation of Joining, i.e. we split the contents of an array to multiple sub-arrays, along a specified axis.
We can either split them into arrays of the same shape or indicate the position after which the split should occur.

In [99]:
arr3 = np.arange(9)
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

#### ◼️ Even Split
np.split(arr3, 3)
will produce 3 equal-sized sub-arrays:

In [100]:
np.split(arr3,3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

#### ◼️ Uneven Split, based on the positions indicated in a 1D array
np.split(arr3, [2, 7]))
will produce 3 sub-arrays, split after the 2nd and 7th elements:

In [103]:
np.split(arr3, [2,7])

[array([0, 1]), array([2, 3, 4, 5, 6]), array([7, 8])]

In [104]:
tobemapped = np.arange(0,10)
tobemapped

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [105]:
np.vectorize(lambda x: x*2)(tobemapped)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### ➒ — Filtering

Filter, tests each element with a unary predicate. NumPy provides the extract function for this. Elements that satisfy the predicate are kept; those that don’t are removed. A new array is returned; filter doesn’t modify the original array.

In [106]:
tobefiltered = np.arange(0,9).reshape(3,3)
tobefiltered

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [107]:
np.extract(tobefiltered % 2== 1, tobefiltered)

array([1, 3, 5, 7])

In [108]:
tobefiltered[tobefiltered % 2 == 1]

array([1, 3, 5, 7])

### ➓ — Reduction

When faced with a large amount of data, a desired step is to reduce the dimensions by applying a calculation across the whole array or over one of its axis.

In [109]:
tobereduce = np.arange(1,7).reshape(2,3)
tobereduce

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
tobereduc